frase=str(input('Digite uma frase: '))
frase=frase.upper()
print(f'{frase}')
vezes=frase.count('A')
print(f'A letra a aparece {vezes} vezes')
prim=(frase.find('A')+1)
ult=(frase.rfind('A')+1)
print(f'A posição do primeiro a é {prim}')
print(f'A posição do último a é {ult}')
